<?php

/**
 * Implementation of hook_init().
 */
function public_voting_init() {
    require_once 'tropo/tropo.class.php';
}

/**
 * Implementation of hook_menu().
 *
 * @return An array of menu items.
 */
function public_voting_menu() {
    $items = array();

    $items['tropo/ask.json'] = array(
        'page callback' => 'tropo_ask',
        'access arguments' => array('access content'),
        'file' => 'includes/public_voting.type.inc',
    );

    $items['tropo/result.json'] = array(
        'page callback' => 'tropo_result',
        'access arguments' => array('access content'),
        'file' => 'includes/public_voting.type.inc',
    );

    $items['tropo/error.json'] = array(
        'page callback' => 'tropo_error',
        'access arguments' => array('access content'),
        'file' => 'includes/public_voting.type.inc',
    );

    return $items;
}

function public_voting_vote($nid, $child) {
    $poll = node_load($nid);

    $form['#node'] = $poll;
    $form_state['values']['choice'] = $child;
    poll_vote($form, $form_state);
}
